--
-- PostgreSQL database dump
--

-- Dumped from database version 15.6 (Debian 15.6-0+deb12u1)
-- Dumped by pg_dump version 15.6 (Debian 15.6-0+deb12u1)

-- Started on 2024-04-30 17:46:03 EEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 847 (class 1247 OID 16431)
-- Name: abonamente; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.abonamente AS ENUM (
    'lunar',
    'anual',
    'bianual'
);


ALTER TYPE public.abonamente OWNER TO postgres;

--
-- TOC entry 838 (class 1247 OID 16392)
-- Name: categorie_produs; Type: TYPE; Schema: public; Owner: codrut
--

CREATE TYPE public.categorie_produs AS ENUM (
    'vps',
    'dedicat',
    'storage',
    'gpu',
    'serverless'
);


ALTER TYPE public.categorie_produs OWNER TO codrut;

--
-- TOC entry 844 (class 1247 OID 16417)
-- Name: centru_date; Type: TYPE; Schema: public; Owner: codrut
--

CREATE TYPE public.centru_date AS ENUM (
    'Falkenstein',
    'London',
    'Chicago',
    'Nagoya',
    'Sidney'
);


ALTER TYPE public.centru_date OWNER TO codrut;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 16403)
-- Name: produse; Type: TABLE; Schema: public; Owner: codrut
--

CREATE TABLE public.produse (
    id bigint NOT NULL,
    nume text NOT NULL,
    descriere text,
    imagine text,
    categorie public.categorie_produs NOT NULL,
    pret bigint NOT NULL,
    pret_configurare bigint DEFAULT 0 NOT NULL,
    data_adaugare timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    specificatii text[],
    disponibil boolean DEFAULT true NOT NULL,
    datacenter public.centru_date DEFAULT 'Falkenstein'::public.centru_date NOT NULL,
    abonamente public.abonamente[] DEFAULT '{lunar}'::public.abonamente[] NOT NULL,
    nr_imagini smallint DEFAULT 2 NOT NULL
);


ALTER TABLE public.produse OWNER TO codrut;

--
-- TOC entry 215 (class 1259 OID 16411)
-- Name: produse_id_seq; Type: SEQUENCE; Schema: public; Owner: codrut
--

ALTER TABLE public.produse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3358 (class 0 OID 16403)
-- Dependencies: 214
-- Data for Name: produse; Type: TABLE DATA; Schema: public; Owner: codrut
--

COPY public.produse (id, nume, descriere, imagine, categorie, pret, pret_configurare, data_adaugare, specificatii, disponibil, datacenter, abonamente, nr_imagini) FROM stdin;
1	VPS Mic	Pentru proiecte personale sau pentru testat servicii.	vps-1	vps	10	0	2024-04-22 16:36:06.1435	{"'2 vCPU'","'4GB RAM'","'40GB SSD'"}	t	Falkenstein	{lunar}	2
2	VPS Mediu	Pentru intreprinderi mici.	vps-2	vps	20	0	2024-04-22 16:37:40.674725	{"'4 vCPU'","'8GB RAM'","'80GB SSD'"}	t	Falkenstein	{lunar}	2
3	VPS Puternic	Pentru intreprinderi medii.	vps-3	vps	40	0	2024-04-22 16:39:41.611056	{"'8 vCPU'","'16GB RAM'","'160GB SSD'"}	t	Falkenstein	{lunar}	2
4	VPS Max	Pentru intreprinderi mari sau cerinte intensive.	vps-4	vps	80	0	2024-04-22 16:42:55.15296	{"'16 vCPU'","'32GB RAM'","'320GB SSD'"}	t	Falkenstein	{lunar}	2
7	Storage Box	Pentru uz personal, prin WebDAV si FTP.	storage-box	storage	16	0	2024-04-22 16:50:58.44143	{"'4TB HDD'"}	t	Chicago	{lunar}	2
8	Storage S3	Pentru intreprinderi care distribuie si modifica date constant.	s3	storage	128	10	2024-04-22 16:50:58.44143	{"'16TB SSD'"}	t	Chicago	{lunar}	2
13	Web Hosting	Pentru pagini personale.	web-host	serverless	16	0	2024-04-22 17:51:19.050941	{"'10 Subdomenii'","'40GB SSD'","'2TB Bandwidth'"}	t	Chicago	{lunar}	2
11	Server Encoding	Pentru randare video sau grafica 3D.	intel-arc	gpu	96	20	2024-04-22 17:02:35.49702	{"'Intel I9-13900k'","'64GB RAM'","'4 x Intel ARC A770 16GB'","'1TB SSD'"}	t	London	{anual,bianual}	2
14	Elastic Container	Scalare verticala a microserviciilor.	ecs	serverless	80	10	2024-04-22 17:57:45.895662	{}	t	London	{lunar}	2
17	email	Gazduire e-mail.	email	serverless	10	0	2024-04-30 12:31:28.770588	{"'50GB stocare'"}	t	Nagoya	{anual,bianual}	2
18	Remote Desktop	Control de la distanta a unei unitati puternice.	remote-desktop	gpu	60	10	2024-04-30 12:31:28.770588	{"'Ryzen 9 5950x'","'RTX 4060TI 16GB'","'1TB M.2 SSD'"}	f	London	{lunar}	2
19	supabase	Mediu de dezvoltare intuitiv pentru logica aplicatiilor.	supabase	serverless	30	0	2024-04-30 12:31:28.770588	{"'20GB baza de date'","'1GB RAM Edge functions'","'1 vCPU Edge functions'"}	f	Chicago	{lunar}	2
5	Dedicat Mic	Pentru servicii centralizate simple.	ded-1	dedicat	160	20	2024-04-22 16:47:19.714134	{"'AMD Ryzen 5 3600'","'64GB RAM'","'4TB SATA HDD'"}	t	Nagoya	{lunar,anual}	3
6	Dedicat mediu	Pentru servicii centralizate intensive.	ded-2	dedicat	280	40	2024-04-22 16:47:19.714134	{"'AMD Ryzen 7 7700'","'128GB RAM'","'2TB SATA HDD'"}	t	Nagoya	{lunar,anual}	3
12	Server IA	Pentru antrenarea inteligentei artificiale.	nvidia-a100	gpu	286	80	2024-04-22 17:02:35.49702	{"'AMD EPYC 9654'","'1024GB RAM'","'16x NVIDIA A100'","'2TB SSD'"}	t	London	{anual,bianual}	4
\.


--
-- TOC entry 3365 (class 0 OID 0)
-- Dependencies: 215
-- Name: produse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: codrut
--

SELECT pg_catalog.setval('public.produse_id_seq', 19, true);


--
-- TOC entry 3215 (class 2606 OID 16409)
-- Name: produse produse_pkey; Type: CONSTRAINT; Schema: public; Owner: codrut
--

ALTER TABLE ONLY public.produse
    ADD CONSTRAINT produse_pkey PRIMARY KEY (id);


-- Completed on 2024-04-30 17:46:03 EEST

--
-- PostgreSQL database dump complete
--

